export const SET_PRODUCT_TO_CART_LIST = "SET_PRODUCT_TO_CART_LIST";
export const SET_PRODUCT_TO_CART_LIST_LOADING =
  "SET_PRODUCT_TO_CART_LIST_LOADING";
export const DELETE_PRODUCT_FROM_CART_LIST = "DELETE_PRODUCT_FROM_CART_LIST";
export const CLEAR_CART = "CLEAR_CART";
export const SET_QUANTITY = "SET_QUANTITY";
export const RESET_REDUX_STATES = "RESET_REDUX_STATES";
export const SET_SIGNUP_USER_LOADING = "SET_SIGNUP_USER_LOADING";
export const SET_LOGIN_USER_LOADING = "SET_LOGIN_USER_LOADING";
