export const SET_SIGNUP_USER_LOADING = "SET_SIGNUP_USER_LOADING";
export const SET_LOGIN_USER_LOADING = "SET_LOGIN_USER_LOADING";
export const SET_SIGNUP_USER = "SET_SIGNUP_USER";
export const SET_LOGIN_USER = "SET_LOGIN_USER";
export const SET_LOGOUT_USER = "SET_LOGOUT_USER";
