export const SET_PRODUCT_TO_CART_LIST = "SET_PRODUCT_TO_CART_LIST";
export const DELETE_PRODUCT_FROM_CART_LIST = "DELETE_PRODUCT_FROM_CART_LIST";
export const CLEAR_CART = "CLEAR_CART";
export const SET_QUANTITY = "SET_QUANTITY";
