// --------------Contacts Details-----------------
const contacts = [
  {
    userId: "contact002",
    firstName: "Master",
    lastName: "Time",
    age: 25,
    gender: "Male",
    zipCode: 93901,
  },
  {
    userId: "contact003",
    firstName: "Acton",
    lastName: "Nisaan",
    age: 26,
    gender: "Male",
    zipCode: 93902,
  },
  {
    userId: "contact004",
    firstName: "Kuluni",
    lastName: "Singh",
    age: 16,
    gender: "Male",
    zipCode: 93905,
  },
  {
    userId: "contact005",
    firstName: "Priyanka",
    lastName: "Mohan",
    age: 26,
    gender: "Female",
    zipCode: 93906,
  },
  {
    userId: "contact006",
    firstName: "Hena",
    lastName: "Mehta",
    age: 32,
    gender: "Female",
    zipCode: 94111,
  },
  {
    userId: "contact007",
    firstName: "Hemant",
    lastName: "Runet",
    age: 22,
    gender: "Male",
    zipCode: 94110,
  },
  {
    userId: "contact008",
    firstName: "Jagdish",
    lastName: "Herunima",
    age: 36,
    gender: "Male",
    zipCode: 94109,
  },
  {
    userId: "contact009",
    firstName: "Anjali",
    lastName: "Mehta",
    age: 36,
    gender: "Female",
    zipCode: 94108,
  },
  {
    userId: "contact0010",
    firstName: "Tarak",
    lastName: "Mehta",
    age: 60,
    gender: "Male",
    zipCode: 94107,
  },
  {
    userId: "contact0011",
    firstName: "Jetha ",
    lastName: "lal",
    age: 12,
    gender: "Male",
    zipCode: 94106,
  },
  {
    userId: "contact0012",
    firstName: "Daya",
    lastName: "Bain",
    age: 35,
    gender: "Female",
    zipCode: 94105,
  },
  {
    userId: "contact0013",
    firstName: "Babita",
    lastName: "ji",
    age: 45,
    gender: "Female",
    zipCode: 94104,
  },
  {
    userId: "contact0014",
    firstName: "Vivan",
    lastName: "Gupta",
    age: 12,
    gender: "Male",
    zipCode: 94103,
  },
  {
    userId: "contact0015",
    firstName: "Mumbai",
    lastName: "Gupta",
    age: 12,
    gender: "Male",
    zipCode: 94102,
  },
  {
    userId: "contact0016",
    firstName: "Somit",
    lastName: "Jinula",
    age: 22,
    gender: "Male",
    zipCode: 94040,
  },
  {
    userId: "contact0017",
    firstName: "Nalin",
    lastName: "Porwal",
    age: 22,
    gender: "Male",
    zipCode: 94039,
  },
  {
    userId: "contact0018",
    firstName: "Mahima",
    lastName: "Kunita",
    age: 32,
    gender: "Female",
    zipCode: 94038,
  },
  {
    userId: "contact0019",
    firstName: "Ankisha",
    lastName: "Jain",
    age: 25,
    gender: "Female",
    zipCode: 94017,
  },
  {
    userId: "contact0020",
    firstName: "Ankit",
    lastName: "Malviya",
    age: 55,
    gender: "Male",
    zipCode: 94016,
  },
  {
    userId: "contact0021",
    firstName: "Aditya",
    lastName: "Arora",
    age: 26,
    gender: "Male",
    zipCode: 94015,
  },
  {
    userId: "contact0022",
    firstName: "Gehna",
    lastName: "Sathiya",
    age: 24,
    gender: "Female",
    zipCode: 94014,
  },
  {
    userId: "contact0023",
    firstName: "Gungun",
    lastName: "Sathiya",
    age: 24,
    gender: "Female",
    zipCode: 94013,
  },
  {
    userId: "contact0024",
    firstName: "Func",
    lastName: "Rathi",
    age: 24,
    gender: "Male",
    zipCode: 94011,
  },
  {
    userId: "contact0025",
    firstName: "Riya",
    lastName: "Singh",
    age: 24,
    gender: "Female",
    zipCode: 94010,
  },
  {
    userId: "contact0026",
    firstName: "Aliya",
    lastName: "Singh",
    age: 24,
    gender: "Female",
    zipCode: 94005,
  },
  {
    userId: "contact0027",
    firstName: "Naveen",
    lastName: "Kumar",
    age: 29,
    gender: "Male",
    zipCode: 94002,
  },
  {
    userId: "contact0028",
    firstName: "Shubham",
    lastName: "Sharma",
    age: 63,
    gender: "Male",
    zipCode: 94132,
  },
  {
    userId: "contact0029",
    firstName: "Shalini",
    lastName: "Sharma",
    age: 32,
    gender: "Female",
    zipCode: 93955,
  },
  {
    userId: "contact0030",
    firstName: "Paresh",
    lastName: "Sahu",
    age: 22,
    gender: "Male",
    zipCode: 93950,
  },
  {
    userId: "contact0031",
    firstName: "Praveen",
    lastName: "Raj",
    age: 25,
    gender: "Male",
    zipCode: 93944,
  },
  {
    userId: "contact0033",
    firstName: "Faruk",
    lastName: "Shek",
    age: 25,
    gender: "Male",
    zipCode: 93942,
  },
  {
    userId: "contact0033",
    firstName: "Shankar",
    lastName: "Kumar",
    age: 25,
    gender: "Male",
    zipCode: 93933,
  },
];

// ------------Agents Details

const agents = [
  {
    userId: "agent002",
    firstName: "Sumit",
    lastName: "Indore",
    age: 28,
    gender: "Male",
    zipCode: 93915,
    profession: "Engineer",
  },
  {
    userId: "agent001",
    firstName: "Aalok",
    lastName: "IMumbai",
    age: 28,
    gender: "Male",
    zipCode: 93912,
    profession: "Doctor",
  },
  {
    userId: "agent003",
    firstName: "Aarchi",
    lastName: "Indore",
    age: 22,
    gender: "Female",
    zipCode: 93907,
    profession: "Lawyer",
  },
];

const credentials = [
  {
    userId: "agent001",
    password: "1234567",
  },
  {
    userId: "agent002",
    password: "1234567",
  },
  {
    userId: "agent003",
    password: "1234567",
  },
  {
    userId: "contact001",
    password: "1234567",
  },
  {
    userId: "contact002",
    password: "1234567",
  },
  {
    userId: "contact003",
    password: "1234567",
  },
  {
    userId: "contact004",
    password: "1234567",
  },
  {
    userId: "contact005",
    password: "1234567",
  },
  {
    userId: "contact006",
    password: "1234567",
  },
  {
    userId: "contact007",
    password: "1234567",
  },
  {
    userId: "contact008",
    password: "1234567",
  },
  {
    userId: "contact009",
    password: "1234567",
  },
  {
    userId: "contact0010",
    password: "1234567",
  },
  {
    userId: "contact0011",
    password: "1234567",
  },
  {
    userId: "contact0012",
    password: "1234567",
  },
  {
    userId: "contact0013",
    password: "1234567",
  },
  {
    userId: "contact0014",
    password: "1234567",
  },
  {
    userId: "contact0015",
    password: "1234567",
  },
  {
    userId: "contact0016",
    password: "1234567",
  },
];

exports.credentials = credentials 
exports.contacts = contacts
exports.agents = agents 